# -*- coding: utf-8 -*-
"""Resume_Predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TaRlJNvzumZclf5M5ere1dlC0n4tdUXa
"""

import pandas as pd
import numpy as np
import re
import string

data = pd.read_csv("UpdatedResumeDataSet.csv")

data.head()

def cleanResume(text):

    text = re.sub(r'http\S+\s*', ' ', text)
    text = re.sub(r'RT|cc', ' ', text)
    text = re.sub(r'#\S+', '', text)
    text = re.sub(r'@\S+', '', text)
    text = re.sub(r'[%s]' % re.escape(string.punctuation), ' ', text)
    text = re.sub(r'[^a-zA-Z ]', ' ', text)
    text = re.sub(r'\s+', ' ', text)

    return text.lower()

data['Resume'] = data['Resume'].apply(cleanResume)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

data["Category"] = le.fit_transform(data["Category"])

X = data["Resume"]

y = data["Category"]

from sklearn.feature_extraction.text import CountVectorizer

bow_transformer = CountVectorizer(analyzer=cleanResume).fit(data['Resume'])

Res_bow = bow_transformer.transform(data['Resume'])

Res_bow

Res_bow.toarray()

from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer().fit(Res_bow)

Res_tfidf = tfidf_transformer.transform(Res_bow)

Res_tfidf.toarray()

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier

from sklearn.pipeline import Pipeline
pipeline = Pipeline([
    ('bow',CountVectorizer()),
    ('tfidf',TfidfTransformer()),
    ('classifier',RandomForestClassifier(n_estimators=100))
    ])

pipeline

pipeline.fit(X_train,y_train)

y_pred = pipeline.predict(X_test)

y_pred

y_test

from sklearn.metrics import confusion_matrix,classification_report

print(confusion_matrix(y_test,y_pred))

print(classification_report(y_test,y_pred))

res1 ="""Career Objective
Seeking a Data Science role.

Skills
Python, SQL, Machine Learning, Deep Learning, Pandas, NumPy, Scikit-learn, TensorFlow, Data Analysis, Power BI.

Projects
Loan Approval Prediction
Resume Classification
Customer Churn Prediction"""

pred1 = pipeline.predict([res1])

category = le.inverse_transform(pred1)

print("Predicted Category:", category[0])

res2 = """Career Objective
Seeking a Java Developer role.

Skills
Java, Spring Boot, Hibernate, JDBC, MySQL, REST API, Git, Maven.

Projects
Bank Management System
Student Management System
Hospital Management System"""

pred2 = pipeline.predict([res2])

category = le.inverse_transform(pred2)

print("Predicted Category:", category[0])

res3 = """Aman Verma

Skills
Python
Flask
Django
REST API
SQLite
MySQL
Git
OOP
Pandas

Projects
Library Management System
Employee Management System
Weather API Project

Experience
Python Developer Intern"""

pred3 = pipeline.predict([res3])

category = le.inverse_transform(pred3)

print("Predicted Category:", category[0])

import pickle

with open("resume.pkl", "wb") as f:
    pickle.dump(pipeline, f)
pickle.dump(le, open('label_en.pkl', 'wb'))

